### PR TITLE
More fitting comment style

### PR DESCRIPTION
**Pull request by tuncer**
Use a more fitting comment style

As discussed:

`//` becomes `--`
`/* */` becomes `{- -}`

### CODE REVIEW

**Comment by tuncer** [comment]
WIP for RFC, and obviously broken at the moment.

**Comment by yurrriq** [comment]
What about Haskell/Idris-style `{- ... -}` for {multi,in}line comments?

**Comment by tuncer** [comment]
@j14159 suggested `(* *)`. I'm fine with either choice.

**Comment by j14159** [comment]
I have a vague aesthetic preference for the OCaml style is all :)

**Comment by yurrriq** [comment]
Ah, the asterisks didn't show up on my phone. +1 for OCaml-style `(* ... *)` then.

**Comment by tuncer** [comment]
FWIW, I do find `{- -}` quicker/easier to type.

**Comment by tuncer** [comment]
Another advantage of `{- -}` is that `-` is always centered vertically, whereas `*` is very often (depending on how and where it's rendered) top-aligned. So, I'm leaning towards `{- -}`. That way, it would also be more conventional in combination with `--`.

**Comment by yurrriq** [comment]
Tbh that's my preference too, but I defer to @j14159.

**Comment by j14159** [comment]
I'm OK with `{- -}` to be honest, not particularly attached to anything and if it's easier to type and align, bonus.  Also maybe less fighting with leex?

**Comment by tuncer** [comment]
Great, I'll update the patch accordingly.

**Comment by tuncer** [comment]
Update done, but the multi-line regex isn't quite right yet, although it mostly matches correctly.

**Comment by tuncer** [comment]
Update done.

**Comment by tuncer** [comment]
While the current regex works, it will misinterpret a `}` that wasn't preceded by `-`. So, `{- fkk}bar -}` won't be parsed correctly. @j14159, any suggestion how to fix that?

**Comment by tuncer** [comment]
I think I solved it. Please review.

**Comment by yurrriq** [comment]
LGTM. I was just writing basically the same patch :smile:. Perhaps we ought to add some stress testing.

**Comment by yurrriq** [comment]
@tuncer, I've submitted a PR to you branch that checks for nested comments.

**Comment by j14159** [comment]
@tuncer I think @yurrriq's addition makes sense as well here, thoughts? (noticed it's not merged on your fork is all)

**Comment by tuncer** [comment]
Sure, I can merge it, but I have a question: where is `nested_comment` handled? Just for me to fully understand what's happening there.

**Comment by tuncer** [comment]
Merged @yurrriq patch.

**Comment by j14159** [comment]
Merging, thanks @tuncer and @yurrriq!

**Pull request merged**
