### PR TITLE
Add basic comments scanner stress test

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
Interestingly `rebar3 eunit` fails to compile `comments.mlfe` for me locally. Tested with 18.3.3, 19.0.3 and 19.0.4.

```
{error,
    {badmatch,
        {error,
            {999999,mlfe_parser,
             ["syntax error before: ",[]]}}},
    [{mlfe_ast_gen,parse_module,2,
...
```

**Comment by yurrriq** [comment]
> Interestingly, eunit fails to compile comments.mlfe for me locally.

Same here...

> Want to send a pull request for the pr's branch?

Will do.

**Comment by yurrriq** [comment]
> Interestingly, `eunit` fails to compile `comments.mlfe` for me locally.

#19 addressed this. I've rebase my branch of this PR and all is well again.

**Comment by yurrriq** [comment]
As noted, you'll need to rebase on j14159/master, but I've opened tuncer/mlfe#2.

**Comment by tuncer** [comment]
Thanks, tuncer/mlfe#2 may need a rebase.

**Comment by tuncer** [comment]
Do you know why it didn't fail to compile on travis-ci?

**Comment by tuncer** [comment]
Should `{- {- illegal nested comment -} -}` really be invalid?

**Comment by j14159** [comment]
@tuncer @yurrriq I don't have a strong opinion on the nested comment error.  I suppose it forces cleaner comments at the expense of being able to quickly comment out chunks of code?

**Comment by yurrriq** [comment]
Well right now the parser can't handle it and without a nice error it just explodes. It seems to me that it shouldn't be a bad match error but rather the underlying error itself.

**Comment by yurrriq** [comment]
@tuncer, your PR failed because it needed #19.

**Comment by tuncer** [comment]
Haskell and OCaml seem to accept nested block comments, so maybe mlfe should as well.

**Comment by tuncer** [comment]
> @tuncer, your PR failed because it needed #19.

This pr succeeded on travis-ci, but it failed for me locally as it did for you. That's what's puzzling.

**Comment by tuncer** [comment]
Maybe we should merge this and defer the invalid comments discussion and tackle it in another pull request. @yurrriq?

**Comment by yurrriq** [comment]
Oops. My brain skipped over the "didn't" in "didn't fail." No idea there. Curious...

**Comment by yurrriq** [comment]
I can open a new PR for the nested comment failure test, but I think it'd be better to improve the parser, such that it supports nested comments, then add a test to confirm successful parsing of nested comments.

**Comment by tuncer** [comment]
> improve the parser, such that it supports nested comments

+1

**Pull request merged**
